### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by frankier** [yonkornilov/opus-api#41]
Hi. I'm kind of interested in using this, but I'm using Python 3 for everything nowadays. It looks like this is intentionally Python 2 only. Would you be interested in moving to Python 3?

**Comment by yonkornilov** [comment]
Hi @frankier, this project being python2 exclusive wasn't intentional. Looking at it now I agree that that moving to python3 would be better.

I would have to take a look at what parts of TravisCI need to be changed for python3 and of course begin the migration within the code as soon as possible. But feel free to fork and submit a PR even before that!

**Comment by frankier** [comment]
Hi! Just to let you know that I probably won't have time to make a PR in the immediate future. At the moment I am using a subprocess with the command line version. I'll let you know in case I decide to work on it later so we don't both.

**Comment by yonkornilov** [comment]
After #47 we are now using Python3, with v0.5.0 being available via pip.
